#!/bin/bash
# Script to update requirements.txt from pyproject.toml using UV
# This should be run whenever dependencies in pyproject.toml are changed

set -e

echo "Updating requirements.txt from pyproject.toml..."

# Export requirements from UV
uv export --no-hashes --format requirements-txt | grep -v -E '^(#|    #|-e \.)' > requirements.txt.tmp

# Add header
cat > requirements.txt << 'EOF'
# This file is auto-generated from pyproject.toml using UV
# DO NOT edit this file directly. Instead, modify pyproject.toml and run: ./update-requirements.sh
#
# This file is used for Google App Engine deployment while UV is used for local development.

EOF

# Append the requirements
cat requirements.txt.tmp >> requirements.txt
rm requirements.txt.tmp

echo "✓ requirements.txt has been updated successfully!"
echo ""
echo "Don't forget to commit the updated requirements.txt:"
echo "  git add requirements.txt"
echo "  git commit -m 'Update requirements.txt from pyproject.toml'"
