import Head from 'next/head'
import React from 'react'

function GCloud () {
  return (<>
        <Head>

        <meta name="description" content="Generated by create next app" />
        <script src="https://accounts.google.com/gsi/client" async defer></script>

        </Head>

        <div id="g_id_onload"
          data-client_id=""
          data-callback="handleCredentialResponse">
        </div>

        <div className="g_id_signin" data-type="standard"></div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        </>
  )
}

export default GCloud
