import Head from 'next/head'
import { Button } from '@mui/material'
import React from 'react'

function SignIn (props) {
  function handleAuthClick () {
    props.googleauth.signIn()
  }

  return (<>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Button id="sign-in-or-out-button" variant="contained" color="primary" onClick={handleAuthClick}>Conectar</Button>
        </>
  )
}

export default SignIn
