import Head from 'next/head'
import { Button } from "@material-ui/core";
import React, { useEffect, useState } from 'react';
import {GOOGLE_API_KEY, CLIENT_ID} from './google'

function SignIn(props) {

  var SCOPE = 'https://www.googleapis.com/auth/devstorage.full_control';
  
  useEffect(() => {
    var script = document.createElement('script');
    script.onload=handleClientLoad;
    script.src="https://apis.google.com/js/api.js";
    document.body.appendChild(script);
  }, [])

  function handleClientLoad() {
    // Load the API's client and auth2 modules.
    // Call the initClient function after the modules load.
    gapi.load('client:auth2', initClient);
  }

  function initClient() {
    // Initialize the gapi.client object, which app uses to make API requests.
    // Get API key and client ID from API Console.
    // 'scope' field specifies space-delimited list of access scopes.
    try{
      gapi.client.init({
        'apiKey': GOOGLE_API_KEY,
        'clientId': CLIENT_ID,
        'scope': SCOPE,
        'discoveryDocs': ['https://www.googleapis.com/discovery/v1/apis/drive/v3/rest']
    }).then(() => {
      // GoogleAuth = gapi.auth2.getAuthInstance();
      props.setgoogleauth(gapi.auth2.getAuthInstance())
    }
    )}
    catch(e){
        console.log(e);}
  }

  function handleAuthClick() {
    console.log("signing in")
    // GoogleAuth.signIn()
    props.googleauth.signIn()
    // if (GoogleAuth.isSignedIn.get()) {
    //   // User is authorized and has clicked "Sign out" button.
    //   GoogleAuth.signOut();
    // } else {
    //   // User is not signed in. Start Google auth flow.
    //   GoogleAuth.signIn();
      
    // }
    console.log(props.googleauth)
    // console.log(props.googleauth.currentUser.Nb.wc.access_token)
  }

  function onSignIn(googleUser) {
    // Useful data for your client-side scripts:
    var profile = googleUser.getBasicProfile();
    console.log("ID: " + profile.getId()); // Don't send this directly to your server!
    console.log('Full Name: ' + profile.getName());
    console.log('Given Name: ' + profile.getGivenName());
    console.log('Family Name: ' + profile.getFamilyName());
    console.log("Image URL: " + profile.getImageUrl());
    console.log("Email: " + profile.getEmail());

    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    console.log("ID Token: " + id_token);
  }

    return (<>
        <Head>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="google-signin-scope" content="profile email"/>
        <meta name="google-signin-client_id" content={CLIENT_ID}/>
     
        
      </Head>
        <Button id="sign-in-or-out-button" variant="contained" color="primary" onClick={handleAuthClick}>Conectar</Button>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        </>
    )
}

export default SignIn