import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Script from 'next/script'
import { Button } from "@material-ui/core";
import React, { useEffect, useState } from 'react';

import Layout from '../components/Layout'
import Typography from '@mui/material/Typography';
import { GreenRadio, RedRadio, YellowRadio } from '../components/RadioButtons'
import { Radio } from '@mui/material'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>ReciclApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/logo.png" />
      </Head>
      <Layout>

        <Typography variant="h4" component="div" gutterBottom>
          Bienvenido/a a ReciclApp
        </Typography>
        <Typography variant="body1" paragraph>
          Si tienes acceso a los datos de Recicla+, conéctate y abre el archivo. 
          En caso contrario, puedes utilizar el documento de ejemplo para explorar la funcionalidad.
        </Typography>

        <Typography variant="h5" gutterBottom>
          Lista
        </Typography>
        <Typography variant="body1" paragraph>
          Visualiza los puntos de recogida en la lista. Filtra por cualquiera de los campos existentes o usa el buscador para encontrar un punto en concreto. También puedes editar un punto dándole click al lápiz y editanto el campo deseado.
        </Typography>

        <Typography variant="h5" gutterBottom>
          Mapa
        </Typography>
        <Typography variant="body1" paragraph>
          Visualiza los puntos de recogida en el mapa. Dale click a uno de los puntos para averiguar el nombre.
        </Typography>

        <Typography variant="h5" gutterBottom>
          Nuevo Punto
        </Typography>
        <Typography variant="body1" paragraph>
          Puedes añadir un punto llenando los campos obligatorios. Si no se llena el campo id, se le asignará el siguiente disponible en su barrio.
        </Typography>

        <Typography variant="h5" gutterBottom>
          Pasar Puntos
        </Typography>
        
        <Typography variant="body1" whiteSpace="pre-line" gutterBottom paragraph>
          Para recoger los datos de la recogida, indica qué puntos tenían plástico cuando pasaste. Los posibles valores son:
        </Typography>  

        <Typography variant="body1" >
          <GreenRadio checked={true} /> Sí: pasé por la casa y sí había plástico
        </Typography>
        
        <Typography variant="body1" >
          <RedRadio checked={true} /> No: pasé por la casa pero no había plástico
        </Typography>

        <Typography variant="body1" >
          <YellowRadio checked={true} /> No disponible: por cualquier razón no pude pasar por la casa (ej. la calle estaba en obras)
        </Typography>

        <Typography variant="body1" paragraph>
          <Radio checked={true} color="default"/> Cerrado: Pasé por la casa pero estaba cerrada
        </Typography>

        <Typography variant="h5" gutterBottom>
          Estadísticas
        </Typography>

        <Typography variant="body1" paragraph>
          Analiza como está evolucionando el proyecto.
        </Typography>

      </Layout>
    </div>
  )
}
